+-------------+---------+
| Column Name | Type    |
+-------------+---------+
| employee_id | int     |
| name        | varchar |
| salary      | int     |
+-------------+---------+
employee_id is the primary key (column with unique values) for this table.
Each row of this table indicates the employee ID, employee name, and salary.
 

Write a solution to calculate the bonus of each employee. The bonus of an employee is 100% of their salary if the ID of the employee is an odd number and the employee's name does not start with the character 'M'. The bonus of an employee is 0 otherwise.

Return the result table ordered by employee_id.

The result format is in the following example.

 

Example 1:

Input: 
Employees table:
+-------------+---------+--------+
| employee_id | name    | salary |
+-------------+---------+--------+
| 2           | Meir    | 3000   |
| 3           | Michael | 3800   |
| 7           | Addilyn | 7400   |
| 8           | Juan    | 6100   |
| 9           | Kannon  | 7700   |
+-------------+---------+--------+
Output: 
+-------------+-------+
| employee_id | bonus |
+-------------+-------+
| 2           | 0     |
| 3           | 0     |
| 7           | 7400  |
| 8           | 0     |
| 9           | 7700  |
+-------------+-------+
Explanation: 
The employees with IDs 2 and 8 get 0 bonus because they have an even employee_id.
The employee with ID 3 gets 0 bonus because their name starts with 'M'.
The rest of the employees get a 100% bonus.

In [ ]:
import pandas as pd

def calculate_special_bonus(employees: pd.DataFrame) -> pd.DataFrame:
    employees['bonus'] = 0

    conditions = ((employees['employee_id'] % 2 == 1) & (~employees['name'].str.startswith('M')))

    employees.loc[conditions, 'bonus'] = employees['salary']

    return employees[['employee_id', 'bonus']].sort_values(by = 'employee_id', ascending = True)

#don't have to include the second loc

In [ ]:
import pandas as pd

def calculate_special_bonus(employees: pd.DataFrame) -> pd.DataFrame:
    employees['bonus'] = 0

    conditions = ((employees['employee_id'] % 2 == 1) & (~employees['name'].str.startswith('M')))

    employees.loc[conditions, 'bonus'] = employees.loc[conditions, 'salary']

    return employees[['employee_id', 'bonus']].sort_values(by = 'employee_id', ascending = True)

In [ ]:
import numpy as np
import pandas as pd

def calculate_special_bonus(employees: pd.DataFrame) -> pd.DataFrame:
    bonus = np.where(
        (employees['employee_id'] % 2 == 1) & (~employees['name'].str.startswith('M')),
        employees['salary'],
        0
    )

    result = pd.DataFrame({
        'employee_id': employees['employee_id'],
        'bonus': bonus
    })

    return result

#this solution is good cause it uses numpy and pandas, it also makes an additional dataframe to work from.
#Also, probably smart to commit pd.DataFrame({key: value, key1: value1})to memory...and remember that fucking
#anything can go in that dataframe.  The indices here will match up, but to explicitly match....

In [ ]:
import pandas as pd
import numpy as np

def calculate_special_bonus(employees: pd.DataFrame) -> pd.DataFrame:
    # Calculate the bonus using numpy.where with combined conditions
    bonus = np.where(
        (employees['employee_id'] % 2 == 1) & (~employees['name'].str.startswith('M')),
        employees['salary'],
        0
    )
    
    # Create the bonus Series to ensure index alignment
    bonus_series = pd.Series(bonus, index=employees.index)
    
    # Create a new DataFrame with the required columns
    result = pd.DataFrame({
        'employee_id': employees['employee_id'],
        'bonus': bonus_series
    })
    
    return result

#rock some shit like this. bonus_series will have the same index as employees