Table: Employee

+-------------+------+
| Column Name | Type |
+-------------+------+
| id          | int  |
| salary      | int  |
+-------------+------+
id is the primary key (column with unique values) for this table.
Each row of this table contains information about the salary of an employee.
 

Write a solution to find the second highest salary from the Employee table. If there is no second highest salary, return null (return None in Pandas).

The result format is in the following example.

 

Example 1:

Input: 
Employee table:
+----+--------+
| id | salary |
+----+--------+
| 1  | 100    |
| 2  | 200    |
| 3  | 300    |
+----+--------+
Output: 
+---------------------+
| SecondHighestSalary |
+---------------------+
| 200                 |
+---------------------+
Example 2:

Input: 
Employee table:
+----+--------+
| id | salary |
+----+--------+
| 1  | 100    |
+----+--------+
Output: 
+---------------------+
| SecondHighestSalary |
+---------------------+
| null                |
+---------------------+

In [ ]:
import pandas as pd 
def second_highest_salary(employee:pd.Dataframe):
    
    unique_salaries = employee['salary'].drop_duplicates(keep = 'first')
    
    if unique_salaries.shape[0] <= 1:
        return pd.DataFrame({'SecondHighestSalary':[None]})

    sorted_salaries = unique_salaries.sort_values(ascending = False)
    
    second_highest = sorted_salaries[1]
    
    second_highest_sal = pd.DataFrame({'SecondHighestSalary' : [second_highest]})
    
    return second_highest_sal